### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by ffoodd** [nico3333fr/jquery-accessible-dialog-tooltip-aria#2]
See the « [publishing npm package](https://docs.npmjs.com/getting-started/publishing-npm-packages) » documentation.

**Comment by nico3333fr** [comment]
Hi,

it is done : https://www.npmjs.com/package/jquery-accessible-dialog-tooltip-aria ;)

`npm i jquery-accessible-dialog-tooltip-aria`

Cheers ! ;)

**Comment by ffoodd** [comment]
🍻
