### ISSUE TITLE
Survol ?

### ISSUE THREAD

**Issue by cyril-lamotte** [nico3333fr/jquery-accessible-dialog-tooltip-aria#4]
Bonjour Nicolas,

Est-ce que ton plugin pourrait marcher avec un tooltip qui s'afficherait au survol plutôt qu'au clic ? et est-ce que ça serait toujours accessible ?

Merci !

**Comment by nico3333fr** [comment]
Hello,

si ça s'affiche en plus au survol mais que ça n'interdit pas le clic, je dirais "pourquoi pas" ? Faudrait ajouter la gestion du hover/pas hover, ça devrait pas être trop difficile.

à la rache : 
``` .on( 'click mouseover ', '.js-tooltip', function( event ) { ```

et dans 
```.on( 'mouseleave', '#js-tooltip', function( event ) {  ```
ajouter 
```
$('#js-tooltip').remove();
```

Évidemment il faudrait câbler ça correctement pour que ça ne le vire que pour un tooltip lancé par le survol de la souris. En fait, faudrait voir le contexte voir si c'est pertinent :)

**Comment by cyril-lamotte** [comment]
Merci pour ta réponse !

**Comment by nico3333fr** [comment]
De rien ;)
